// Minimal secure adapter: the browser sends only a game description here.
// Run: HF_TOKEN=hf_... node backend/server.js
import http from 'node:http';
const port=Number(process.env.PORT||8787), token=process.env.HF_TOKEN||'', model=process.env.HF_MODEL||'HuggingFaceTB/SmolLM3-3B';
const allowed=process.env.ALLOWED_ORIGIN||'*';
const schema=`Return ONLY JSON: {"events":[{"id":"enemy|coins|lives|jump|gameover|scene|controls|colors|base","label":"Spanish label","detail":"short Spanish detail"}]}. No markdown. Extract game mechanics from the user idea.`;
function send(res,status,obj){res.writeHead(status,{'content-type':'application/json; charset=utf-8','access-control-allow-origin':allowed,'access-control-allow-headers':'content-type','access-control-allow-methods':'POST,OPTIONS'});res.end(JSON.stringify(obj));}
function parseModel(x){let s=Array.isArray(x)?(x[0]?.generated_text||''):x?.generated_text||x?.[0]?.generated_text||'';const m=String(s).match(/\{[\s\S]*\}/);if(!m)throw Error('model did not return JSON');const out=JSON.parse(m[0]);if(!Array.isArray(out.events))throw Error('events[] missing');return {events:out.events.slice(0,40).map((e,i)=>({id:String(e.id||'remote_'+i),label:String(e.label||e.type||'Evento IA').slice(0,80),detail:String(e.detail||e.description||'').slice(0,180)}))};}
async function main(req,res){if(req.method==='OPTIONS')return send(res,204,{});if(req.method!=='POST')return send(res,405,{error:'POST only'});if(!token)return send(res,503,{error:'Backend is not configured: set HF_TOKEN server-side'});let body='';for await(const c of req){body+=c;if(body.length>12000)break}let input;try{input=JSON.parse(body)}catch{return send(res,400,{error:'invalid JSON'})}const prompt=String(input.prompt||'').trim();if(!prompt||prompt.length>4000)return send(res,400,{error:'prompt required (max 4000 chars)'});const hf=await fetch(`https://api-inference.huggingface.co/models/${encodeURIComponent(model)}`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({inputs:`${schema}\nUser idea: ${prompt}`,parameters:{max_new_tokens:400,return_full_text:false}})});if(!hf.ok)return send(res,502,{error:`Inference provider HTTP ${hf.status}`});try{return send(res,200,parseModel(await hf.json()))}catch(e){return send(res,502,{error:'Provider response was not valid events JSON'})}}
http.createServer((req,res)=>main(req,res).catch(()=>send(res,500,{error:'adapter failure'}))).listen(port,()=>console.log(`IA adapter listening on http://localhost:${port}`));
